### ISSUE TITLE
Browser.OpenAsync did not open a new page

### ISSUE THREAD

**Issue by qcjxberin** [brminnick/HackerNews#14]
Browser.OpenAsync did not open a new page

**Comment by brminnick** [comment]
Hi @qcjxberin,
Can you provide more information and include a reproduction sample?

OpenBrowserAsync is not triggered for certain HackerNews articles. Is this what you're referring to?

https://github.com/brminnick/HackerNews/blob/ef24c00669489fe6d28422c31353c48c8019ed9d/HackerNews/HackerNews/Pages/NewsPage.cs#L67

**Comment by qcjxberin** [comment]
There is no problem, I recompile and deploy it and it is OK.
